### ISSUE TITLE
Can't install agent on k8s 1.4 

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/launcher#101]
At the moment the agent manifest will only work with kubernetes 1.6+, and until kubernetes supports migration objects api versions.

We could pass the k8s version to the agent URL and serve bespoke manifests.  Maybe using ksonnet?

```
 $ curl -Ls https://get.dev.weave.works | sh -s -- --token=idsx4s8oqxcohdhhy6gg1ta7kn9irpdt
Downloading the Weave Cloud installer...  
Installing Weave Cloud agents on minikube at https://192.168.99.100:8443
There was an error applying the agent: error validating "https://get.dev.weave.works/k8s/agent.yaml": error validating data: [API version "rbac.authorization.k8s.io/v1beta1" isn't supported, only supports API versions ["v1" "apps/v1alpha1" "autoscaling/v1" "certificates.k8s.io/v1alpha1" "extensions/v1beta1" "policy/v1alpha1" "rbac.authorization.k8s.io/v1alpha1" "federation/v1beta1" "storage.k8s.io/v1beta1" "authorization.k8s.io/v1beta1" "batch/v1" "batch/v2alpha1" "componentconfig/v1alpha1" "authentication.k8s.io/v1beta1"], API version "rbac.authorization.k8s.io/v1beta1" isn't supported, only supports API versions ["certificates.k8s.io/v1alpha1" "extensions/v1beta1" "policy/v1alpha1" "rbac.authorization.k8s.io/v1alpha1" "federation/v1beta1" "v1" "apps/v1alpha1" "autoscaling/v1" "storage.k8s.io/v1beta1" "authentication.k8s.io/v1beta1" "authorization.k8s.io/v1beta1" "batch/v1" "batch/v2alpha1" "componentconfig/v1alpha1"]]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by leth** [comment]
We propbably also want [bootstrap to report kubectl & k8s versions](https://github.com/weaveworks/launcher/issues/105).

**Comment by LiliC** [comment]
Since we only support 1.6 onwards, we can close this I think?

**Comment by LiliC** [comment]
@dlespiau Is it worth the effort of supporting those clusters? Think would useful to see how many users are actually still using the 1.4 clusters, and if it's a high %... WDYT?

**Comment by leth** [comment]
We /should/ now have data on these install events in sentry, we should look at to see how often this occurs, and what versions hit out minimum version check!

**Comment by dlespiau** [comment]
I don't currently see any indication in sentry people are trying the installer on 1.4/1.5
