### ISSUE TITLE
Bootstrap should report kubectl & k8s version along with errors

### ISSUE THREAD

**Issue by leth** [weaveworks/launcher#105]
This would greatly help us in reproducing errors!

**Comment by aaron7** [comment]
and the extenal instance id would be very useful. related to https://github.com/weaveworks/launcher/issues/73#issuecomment-364893497

**Comment by dlespiau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bootstrap should report kubectl & k8s version along with errors](https://trello.com/c/4Zpf4mQL/302-bootstrap-should-report-kubectl-k8s-version-along-with-errors)
