### ISSUE TITLE
sentry error: "Discarded value for 'tags' due to exceeding maximum length Collapse"

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/launcher#134]
We may be sending too much data along with the error. We need to check the various limits (tags, message length, ....)

**Comment by leth** [comment]
IIRC the error on the page tells you which tags were dropped.

**Comment by dlespiau** [comment]
I can't find the sentry event any longer, but it was one of the kubectl version fields.

The other issue is that I did something a bit silly with the gke gcloud error and put it in a tag. It should be part of the message I believe: https://github.com/weaveworks/launcher/blob/master/bootstrap/main.go#L95

**Comment by dlespiau** [comment]
Ah, found the error again:
```
[
kubectl_clientVersion_gitTreeState, 
clean
]
```

Quite a few of the `kubectl_` tags could be discarded, they're not really useful.
