### ISSUE TITLE
Better error message for: " There was an error creating the secret"

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/launcher#136]
This is the first operation bootstrap does on the cluster, so it get all sorts of reaonss "the secret"? It could be better worded or indicate more generally that we can't access the api server. Sample error message:

```
There was an error creating the secret: The connection to the server 10.0.0.123:6443 was refused - did you specify the right host or port?

```

**Comment by leth** [comment]
This was fixed by #142 with the server version check
