### ISSUE TITLE
agent.poll-url InstanceID not filled in

### ISSUE THREAD

**Issue by rade** [weaveworks/launcher#139]
when I `kubectl describe` my brand new (installed a few moments ago) weave-agent, I get...
```...
    Args:
      -agent.poll-url=https://get.weave.works/k8s/agent.yaml?instanceID={{.InstanceID}}
...
```
That `{{.InstanceID}}` should have been replaced with the actual id.

**Comment by dlespiau** [comment]
This isn't a bug after all. The argument is a template itself: 

https://github.com/weaveworks/launcher/blob/master/agent/main.go#L27
https://github.com/weaveworks/launcher/blob/master/agent/main.go#L164

We're using this data in bi and I even reviewed the issue, pointing out a bug. Oh well, I blame the late hour.

**Comment by rade** [comment]
Now that you mention it, I actually remember reading the PR that introduced this.
