### ISSUE TITLE
Create Helm chart for launcher agent

### ISSUE THREAD

**Issue by aaron7** [weaveworks/launcher#170]
We would like to provide an option to install Weave Cloud via a Helm chart.

**Comment by stefanprodan** [comment]
@aaron7 can you please do a sem ver release for the launcher agent as in `1.0.0`. I needed it for this PR https://github.com/kubernetes/charts/pull/5163#pullrequestreview-117045040

**Comment by stefanprodan** [comment]
Thanks @aaron7 

I will close this issue once my PR gets merged.

**Comment by dlespiau** [comment]
Your helm PR hash been merged. Closing!
