### ISSUE TITLE
False positive in DNS check during healhcheck cronjob

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/launcher#199]
#We have an hourly healthcheck that tries to install WC on a test instance. Sometimes, the DNS pre-flight check fails there, presumably because something in minikube isn't ready (could be kube-dns?).

```
####################################
### Healthcheck of get.weave.works install script
####################################
• Set WEAVE_CLOUD_TOKEN if it is not already set
• Install Weave Cloud on the minikube cluster
Downloading the Weave Cloud installer...  
Preparing for Weave Cloud setup
Checking kubectl & kubernetes versions
Connecting cluster to "Weave Cloud Launcher Integration tests" (id: xxxx) on Weave Cloud
Installing Weave Cloud agents on minikube at https://10.142.1.137:8443
Performing a check of the Kubernetes installation setup.
There was an error while performing a DNS check: timed out during DNS check. Please check that your cluster can download images and run pods.Exited with code 111
```

**Comment by LiliC** [comment]
Yes, my suspicion was also that not everything is finished in the K8s cluster setup, I would do a preflight check (if we don't have one) after starting minikube, so we know that everything is up and running, or just do a sleep? :)

**Comment by dlespiau** [comment]
we could start with a sleep (10s?), that's cheap to add and, if it helps, we could decide how to test dns is ready when launching minikube.

**Comment by LiliC** [comment]
Cool will add a sleep, can test to see aprox. how long it takes on my machine.

**Comment by LiliC** [comment]
And judging by the circle-ci times, that might indeed be what is happening, as it takes around 45 seconds to get from when it creates a cluster to when it starts the preflight check https://circleci.com/gh/weaveworks/launcher/8398.

**Comment by rade** [comment]
Could this be the same issue that some users are seeing, and for which we introduced #200?

**Comment by LiliC** [comment]
IMO I think they are two different problems, we just were testing a bit too early after setting up the k8s cluster. But I could be wrong.

We should maybe add some output of kube-system namespace resources on build failures, to easier debug this, as it's hard to reproduce. But also to debug other random flakes we have in our tests.

**Comment by dlespiau** [comment]
We should absolutely dump the cluster state and events on errors! mind filing an issue, at least?

**Comment by dlespiau** [comment]
Current status: kube-dns hasn't started yet when we run the test:

```
NAMESPACE     NAME                                                                 READY     STATUS              RESTARTS   AGE
kube-system   po/kube-addon-manager-default-57efe57f-dc69-4d09-8fc4-4d913332e56c   1/1       Running             0          1m
kube-system   po/kube-dns-54cccfbdf8-9g6wz                                         0/3       ContainerCreating   0          19s
kube-system   po/kubernetes-dashboard-77d8b98585-zmz68                             0/1       ContainerCreating   0          19s
kube-system   po/storage-provisioner                                               0/1       ErrImagePull        0          20s
weave         po/launcher-pre-flight-a58ea60305b156c0                              1/1       Terminating         0          1m
```
