### ISSUE TITLE
Listen for an AWS ConfigMap and install cloud-watch exporter

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/launcher#210]
We'd like to expose CloudWatch metrics to Weave Cloud instances and need to install cloudwatch-exporter when configured accordingly. How about:

- Storing AWS credentials in a secret
- Watching for a well-known ConfigMap name in the weave ns, eg. `aws`
- ConfigMap has:
  - region
  - name of the secret with the AWS credentials
- When detecting both the CM and Secret (or any changes in those), curl an Weave Cloud entry point to get the cloudwatch-exporter manifests
- Deletion of the resources should lead to the removal of cloudwatch-exporter (maybe after a grace period, could be the subject a different PR).

**Comment by dlespiau** [comment]
Fixed by https://github.com/weaveworks/launcher/pull/217!

**Comment by LiliC** [comment]
Wanted to leave this open because the deletion part was not done yet, but can open a separate issue for that?

**Comment by dlespiau** [comment]
Ah of course, makes sense, as you wish! A new issue would nice to mark progress by closing issues and to have a better defined goal as your PR implemented 80% if this issue.
