### ISSUE TITLE
agent: On delete of configmap or secret remove Cloudwatch resources

### ISSUE THREAD

**Issue by LiliC** [weaveworks/launcher#219]
On delete we currently don't do anything. We need to somehow detect which resources we deployed and delete them one by one.

cc @dlespiau 

Leftover from https://github.com/weaveworks/launcher/issues/210

**Comment by LiliC** [comment]
cc @marccarre @dlespiau any preferences or other thoughts/suggestions?

**Comment by dlespiau** [comment]
Would changing the generated manifests to not include the `weave` namespace and do `kubectl delete -f` be a better option?

**Comment by LiliC** [comment]
I would then prefer option 3. Change generated manifest to not include the weave ns and delete each individual resource via the k8s api. That's the cleanest and proper way IMO.

**Comment by LiliC** [comment]
As discussed earlier we decided that doing it with [ownerReferences](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/) might be better choice.
Example:
```
  ownerReferences:
    - kind: ConfigMap
      apiVersion: v1
      name: cloudwatch
      uid: <random-uid-here>
```

But I think this might after all be easier to be done in the launcher, as we would need to pass at least the resource `name` and the resource `uid`. So in total we would need to pass onwards 4 more values. And besides that we would need to hardcode the `apiVersion` and `kind`, albeit those api versions have not changed in a while, I think. WDYT @marccarre @dlespiau

**Comment by dlespiau** [comment]
It's not shocking to me to have the full deletion logic in the launcher, that's generic-ish code that could be reused if we do something like this again, which is not unlikely!

**Comment by LiliC** [comment]
Note: Only "problem" with creating an `ownerReference` is we need to add both a reference to the `Secret` and the `ConfigMap` but for that both need to be deleted for the resources that reference them to be removed by k8s. But I guess that is the correct way of doing it anyways IMO.
