### ISSUE TITLE
CI: Move away from https://circleci.com/gh/weaveworks/launcher/edit#aws

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/launcher#239]
There's a big warning there:

> After August 31, 2018, these project settings will no longer be available. Please migrate to CircleCI 2.0.

We can just use the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env variables instead

**Comment by LiliC** [comment]
Changed to the env var and they have worked as the tests pass for https://github.com/weaveworks/launcher/pull/242 which was opened after the change.

Also had a look at other settings that will be deprecated with 1.0 version (parallelism, build env, etc.) and it seems like we don't use those. ✅
