### ISSUE TITLE
Enable advanced configuration options 

### ISSUE THREAD

**Issue by bricef** [weaveworks/launcher#244]
This doesn't need to be published to customers, but most serious users will need some way to (in priorities of requests):

1. Configure the prometheus agents from "Scrape everything" to "Scrap what I tell you to". 
2. Disable scope write access
3. Disable scope altogether

@dlespiau suggested a CRD with a flag map, so that launcher would react to changes to that CRD and I think that would work perfectly.

**Comment by rade** [comment]
Dup of #145
