### ISSUE TITLE
Generic vs Minikube Agent install - Error looking up Weave Cloud instance: Invalid token

### ISSUE THREAD

**Issue by ngehani** [weaveworks/launcher#246]
I have version 1.10.0 of Minikube cluster running on a local laptop (OS X)

I tried using Minikube environment and copied the command and it failed to install agents

Then I tried using Generic environment and copied the command and it worked fine. 

Why the difference?

`[neil@Neils-MacBook-Pro ~/Downloads] 16:37:12 $ curl -Ls https://get.weave.works | sh -s -- --token=xxx

Downloading the Weave Cloud installer...
Preparing for Weave Cloud setup
Checking kubectl & kubernetes versions
Error looking up Weave Cloud instance: Invalid token

[neil@Neils-MacBook-Pro ~/Downloads] 16:41:17 $ curl -Ls https://get.dev.weave.works | sh -s -- --token=xxx

Downloading the Weave Cloud installer...
Preparing for Weave Cloud setup
Checking kubectl & kubernetes versions
Connecting cluster to "Falling Darkness 67" (id: falling-darkness-67) on Weave Cloud
Installing Weave Cloud agents on minikube at https://192.168.99.100:8443
Performing a check of the Kubernetes installation setup.
Successfully installed.

[neil@Neils-MacBook-Pro ~/Downloads] 16:42:19 $`

The token looks the same to me and the command line looks identical

**Comment by LiliC** [comment]
Not sure what went wrong, but the install doesn't differ when it's minikube or generic k8s install IIRC. Maybe there was a glitch with weave cloud itself? Have you tried reproducing it?

**Comment by dlespiau** [comment]
The difference between those 2 commands:
- ` https://get.weave.works`
- `https://get.dev.weave.works`

If this instance is on dev, prod doesn't know about the token and return the error "invalid token"

**Comment by dlespiau** [comment]
I also checked and all the Kubernetes install options in dev are mentioning ` get.dev.weave.works`, which is the right one. Closing then (please use get.dev.weave.works when installing on a dev instance!).
