### ISSUE TITLE
Include more fluxd flags in the requested launch configuration

### ISSUE THREAD

**Issue by squaremo** [weaveworks/launcher#277]
At present, most customisations of fluxd (a.k.a., weave-flux-agent) will be reset when the launcher agent re-applies configuration.

In the absence of a redesign of how that mechanism works, we can at least add some of the flags from fluxd to those that can be configured by supplying them in the URL.

These would be useful to scrape and use in the URL, if present in the deployment manifest:

 - `--registry-ecr-region` ([]string)
 - `--registry-require` ([]string, but in practice either `ecr` or not supplied)
 - `--git-timeout` (duration e.g., `30s`)
 - `--git-poll-interval` (duration e.g., `2m`)
 - `--sync-garbage-collection` (bool)
 - `--memcached-service` (string; especially useful is the ability to set it to empty, implying the memcached service should _not_ have `clusterIP: None`)
 - `--registry-exclude-image` ([]string)
 - `--k8s-allow-namespace` ([]string)
 - `--git-set-author` (bool)
 - `--git-ci-skip` (bool)

**Comment by bboreham** [comment]
This is a subset of #78, I think.  #145 was a possible way to implement.

**Comment by squaremo** [comment]
> This is a subset of #78, I think.

Perhaps, but that advocates for a general mechanism for round-tripping flag values. This issue is asking for an application of the existing, specific mechanism to additional flags. (If a solution to #78 is imminent, then it would be better to expand _that_. But I do not believe it is imminent.)

> #145 was a possible way to implement.

That's a possible way to implement #78, but is not what's requested here.
