### ISSUE TITLE
Make some memcached arguments (for fluxd) configurable

### ISSUE THREAD

**Issue by hiddeco** [weaveworks/launcher#284]
#279 took care of the `weave-flux-agent` arguments, there is however also an edge case scenario in which the default settings for the `weave-flux-memcached` deployment are insufficient.

E.g. when a Weave Cloud user has thousands of tags for one image, the `-I 5m` argument must likely be increased as the metadata for all image tags will not fit into this default (and Flux will start logging `SERVER_ERROR object too large for cache` errors).

The configurability of the following arguments on the memcached deployment would be useful:

- `-m` (integer)
- `-I` (string)

A full description of both arguments can be found on the [memcached man page](https://linux.die.net/man/1/memcached).

**Comment by bobbytables** [comment]
We just hit the error where the object is too big to store in memcache. If you're using GCR like we are, I found a neat script that will delete images older than a certain date:

https://gist.github.com/ahmetb/7ce6d741bd5baa194a3fac6b1fec8bb7
