### ISSUE TITLE
Only ask for secret replacement if it's a different one than the one already there

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/launcher#59]
The way I read the code:https://github.com/weaveworks/launcher/blob/12815eb19bf4c8d62072e77b7d26c87aae8e2df4/bootstrap/main.go#L95 we're always asking if the user wants to replace the secret (with a somewhat confusing message). We could do better by not asking if the stored secret and the incoming one are are the same.

**Comment by rade** [comment]
We could just _not_ prompt ever. That would certainly be an improvement on the status quo. We could also _inform_ the user, without prompting.

**Comment by dlespiau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove or narrow down the boostrap prompt about the weave-cloud secret](https://trello.com/c/1ZazlFpc/301-remove-or-narrow-down-the-boostrap-prompt-about-the-weave-cloud-secret)
